name    'hiera-s3'
version '0.0.0'
source 'http://github.com/codwazny/hiera-s3'
author 'codwazny'
license 'BSD'
summary 'S3 back end for Hiera'
description 'S3 back end for Hiera'
project_page 'http://github.com/codwazny/hiera-s3'
